//Action Types
export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const HANDLER_LOADING = 'HANDLER_LOADING'
export const SET_LOADING = 'SET_LOADING';
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';